create table if not exists public.polter (
  id bigint generated by default as identity primary key,
  quelle_datei text,
  bereitstellung text,
  lieferant text,
  vertragsnummer text,
  datum text,
  holzliste text,
  hab text,
  los text,
  polter_nr text,
  holzart text,
  sortiment text,
  laenge_m double precision,
  stueck double precision,
  menge_rm_original double precision,
  menge_rm_aktuell double precision,
  kubatur_fm_original double precision,
  kubatur_fm_aktuell double precision,
  einheit text,
  lat double precision,
  lon double precision,
  waldort text,
  lagerort text,
  bemerkung text,
  ansprechpartner text,
  zertifikat text,
  status text default 'Offen',
  interne_notiz text default '',
  importiert_am text,
  geaendert_am text
);

alter table public.polter enable row level security;

create policy "allow all for app"
on public.polter
for all
using (true)
with check (true);
